pipeline {
    agent any
    tools {
    maven 'maven'
    }
        
    
    stages {
        stage('build') {
            steps {
              sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deployment') {
            steps {
               script {
    echo "Sending artifacts to machine at " + remoteDirectory

    // Use of the ssh publisher plugin over SSH
    sshPublisher(
        failOnError: false,
        publishers: [
            sshPublisherDesc(
                configName: "deployment",
                transfers: [
                    sshTransfer(
                        sourceFiles: my-app-1.0-SNAPSHOT.jar,
                        remoteDirectory: /opt,
                        flatten: true,
                        execCommand: top,
                        execTimeout: 1800000
                    )
                ],
                sshRetry: [
                    retries: 0
                ]
            )
        ]
    )
 )
     // How can I get the output of execCommand?
    // If the exit code was 1, I want to perform some special steps
    // I'd also like to include the output of the command in these steps
              }
           }
        }
    }
}
