pipeline {
    agent any
    tools {
    maven 'maven'
    }
        
    
    stages {
        stage('build') {
            steps {
              sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deployment') {
            steps {
               script {
                   sshPublisher(publishers: [sshPublisherDesc(configName: 'deployment', transfers: [sshTransfer(cleanRemote: false, excludes: '', execCommand: '', execTimeout: 120000, flatten: false, makeEmptyDirs: false, noDefaultExcludes: false, patternSeparator: '[, ]+', remoteDirectory: '/opt', remoteDirectorySDF: false, removePrefix: 'deployment', sourceFiles: '\'**/*.jar\'')], usePromotionTimestamp: false, useWorkspaceInPromotion: false, verbose: false)])
                }
           }
    }
}
