pipeline {
        agent none
        stages {
          stage('Sonarqube') {
    environment {
         def scannerHome = tool 'Sonar';
    }
    steps {
        withSonarQubeEnv('sonar') {
            sh "${scannerHome}/bin/sonar"
        }
        timeout(time: 10, unit: 'MINUTES') {
            waitForQualityGate abortPipeline: true
         }
     }
 }
     
        }
